baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "Audio Electronics Learning Lab"

[params]
  author = "Nigel Surtees"
  description = "A structured, audio-focused electronics learning notebook."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[taxonomies]
  tag = "tags"

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menus.main]]
    name = "Learning Framework"
    pageRef = "/learning_framework"
    weight = 2

  [[menus.main]]
    name = "Technical Notes"
    pageRef = "/notes"
    weight = 3

  [[menus.main]]
    name = "Exercises"
    pageRef = "/exercises"
    weight = 4
