[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menus.main]]
    name = "Learning Framework"
    pageRef = "/learning_framework"
    weight = 2
  
  [[menus.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5


  [[menus.main]]
    name = "Glossary"
    pageRef = "/learning_framework/glossary"
    weight = 6

  [[menus.main]]
    name = "Search"
    pageRef = "/learning_framework/search"
    weight = 7

  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 10
